#默认打造配置文件名
commonMakeDataName: "commonMakeData"
#菜单设置
Menu:
  #  菜单标题
  Title: "打造菜单"
  #  菜单布局，*为玻璃，-为玻璃框，0为空栏，1为装备槽，2为强化按钮
  Slots:
    - '*********'
    - '*0000000*'
    - '*-------*'
    - '*-1---2-*'
    - '*-------*'
    - '*********'
  #  玻璃名字
  GlassName: "边框"
  #  玻璃框名字
  GlassPaneName: "玻璃框内放装备/图纸"
  #  打造按钮名字
  MakeButtonName: "打造"
#  关键字
KeyWord:
  #  打造关键字
  Make: "可打造"
  #  数值变化关键字
  AddValue: "数值变化"
  #  所需材料关键字
  RequireMaterial: "所需材料"
  #  成功率关键字
  SuccessRate: "成功率"
  #  装备损坏关键字
  Break: "装备损坏"
  #  幸运值关键字
  LuckValue : "LuckValue"
